# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/

title: Joe Dockrill
description: Mumbling About Data Science
github_username: joedockrill
# you can comment the below line out if your repo name is not different than your baseurl
github_repo: "blog"

author:
  name: "Joe Dockrill"
  email: "joedockrill@gmail.com"
  
url: "https://joedockrill.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/blog" # the subpath of your site, e.g. "/blog".

# Github and twitter are optional:
minima:
  social_links:
    github: joedockrill
    linkedin: joe-dockrill

permalink: /:year/:month/:day/:slug/

# Set this to true to get LaTeX math equation support
use_math: 

show_description: true
show_image: false
annotations: false
show_tags: true
google_analytics: UA-175488888-1

exclude:
  - docker-compose.yml
  - action.yml
  - Makefile

# this setting allows you to keep pages organized in the _pages folder
include:
  - _pages

default_badges:
  github: true
  binder: false
  colab: true

# Escape HTML in post descriptions
html_escape:
  description: false

# Everything below here should be left alone. Modifications may break fastpages
future: true
theme: minima
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-octicons
  - jekyll-toc
  - jekyll-twitter-plugin
  - jekyll-relative-links
  - jekyll-seo-tag
  - jekyll-remote-theme
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji

# See https://jekyllrb.com/docs/pagination/
# For pagination to work, you cannot have index.md at the root of your repo, instead you must rename this file to index.html
paginate: 15
paginate_path: /page:num/

remote_theme: jekyll/minima

titles_from_headings:
  enabled:     true
  strip_title: true
  collections: true

highlighter: rouge
markdown: kramdown
kramdown:
  math_engine: katex
  input: GFM
  auto_ids: true
  hard_wrap: false
  syntax_highlighter: rouge
